version: '3'

services:
  sparsh-api:
    container_name: sparsh-api
    image: sparsh-api:latest
    build:
      context: api/src
    command: gunicorn -w 4 --preload -b 0.0.0.0:5001 'app:create_app()'
    ports:
      - "5001:5001"
    depends_on:
      - db
    restart: always
    volumes:
      - ./volumes/app:/app/data
    networks:
      sparsh-network:
        aliases:
          - sparsh-api

  db:
    container_name: db
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    restart: always
    networks:
      sparsh-network:
        aliases:
          - db
    
  unit:
    container_name: unit
    image: unit:latest
    build:
      context: api/tests/unit
    command: pytest
    depends_on:
      - sparsh-api
    networks:
      sparsh-network:
        aliases:
          - unit

  integration:
    container_name: integration
    image: integration:latest
    build:
      context: api/tests/integration
    command: pytest
    depends_on:
      - sparsh-api
      - db
    networks:
      sparsh-network:
        aliases:
          - integration

  e2e:
    container_name: e2e
    image: e2e:latest
    build:
      context: api/tests/e2e
    command: pytest
    depends_on:
      - sparsh-api
      - db
    networks:
      sparsh-network:
        aliases:
          - e2e

  api-infra:
    container_name: api-infra
    image: api-infra:latest
    build:
      context: infra
    networks:
      sparsh-network:
        aliases:
          - api-infra

networks:
  sparsh-network:
    name: sparsh-network
    driver: bridge
