version: '3'

services:
  web:
    image: web:latest
    container_name: web
    build:
      context: src
    command: python3 app.py
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    volumes:
      - ./app:/app
    networks:
      dev:

  db:
    image: mysql:latest
    container_name: db
    build:
      context: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      dev:

  tests:
    extends:
      file: ./tests/docker-compose.yml
      service: tests
    image: tests:latest
    container_name: tests
    build:
      context: tests
    command: pytest
    depends_on:
      - db
      - web
    networks:
      dev:

  terraform:
    image: infra:latest
    container_name: terraform
    build:
      context: infra
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["terraform", "apply", "-auto-approve"]
    networks:
      dev:

networks:
  dev:
