version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.src
    command: python3 app.py
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    depends_on:
      - db
    restart: always
    volumes:
      - ./app:/app

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdbname
      MYSQL_USER: yourusername
      MYSQL_PASSWORD: yourpassword
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  integration_tests:
    build:
      context: .
      dockerfile: Dockerfile.src.tests.integration
    command: pytest
    depends_on:
      - db
      - web
    volumes:
      - ./app:/app
      - ./tests:/tests

  terraform:
    image: infra:latest
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ENV: ${ENV}
    command: ["terraform", "apply", "-auto-approve"]
