version: '3'

services:
  sparsh-api:
    image: sparsh-api:latest
    container_name: sparsh-api
    build:
      context: ./api/src
    env_file:
      - ./api/src/.env
    command: gunicorn -w 4 --preload -b 0.0.0.0:5001 'app:create_app()'
    ports:
      - "5001:5001"
    depends_on:
      - db
    restart: always
    volumes:
      - app:/app/data
    networks:
      - sparsh-network

  db:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: db
    ports:
      - "8000:8000"
    volumes:
      - ./docker/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    restart: always
    networks:
      sparsh-network:
          aliases:
              - unit
    
  unit:
    image: unit:latest
    container_name: unit
    build:
      context: ./api/tests/unit
    environment:
      APP_ENV: test
      COMPOSE_PROJECT_NAME: sparsh
    command: pytest
    depends_on:
      - sparsh-api
    networks:
      sparsh-network:
        aliases:
          - unit

  integration:
    image: integration:latest
    container_name: integration
    build:
      context: ./api/tests/integration
    environment:
      APP_ENV: test
      COMPOSE_PROJECT_NAME: sparsh
    command: pytest
    depends_on:
      - sparsh-api
      - db
    networks:
      sparsh-network:
        aliases:
          - integration

  e2e:
    image: e2e:latest
    container_name: e2e
    build:
      context: ./api/tests/e2e
    environment:
      APP_ENV: test
      COMPOSE_PROJECT_NAME: sparsh
    command: pytest
    depends_on:
      - sparsh-api
      - db
    networks:
      sparsh-network:
        aliases:
          - e2e

  api-infra:
    image: api-infra:latest
    container_name: api-infra
    build:
      context: infra
    environment:
      APP_ENV: prod
      COMPOSE_PROJECT_NAME: sparsh
    networks:
      sparsh-network:
        aliases:
          - api-infra

volumes:
  app:
  dynamodb:

networks:
  sparsh-network:
    driver: bridge
