version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.src
    command: python3 app.py
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    depends_on:
      - db
    restart: always
    volumes:
      - ./app:/app

  db:
    image: postgres:12
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  integration_tests:
    build:
      context: .
      dockerfile: Dockerfile.src.tests.integration
    command: pytest
    depends_on:
      - db
      - web
    volumes:
      - ./app:/app
      - ./tests:/tests

  terraform:
    image: my-app:latest
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ENV: ${ENV}
    command: ["terraform", "apply", "-auto-approve"]
