version: '3'

services:
  sparsh-api:
    image: sparsh-api:latest
    container_name: sparsh-api
    build:
      context: src
    command: gunicorn -w 4 'app:create_app()'
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    # volumes:
    #   - ./app:/app
    networks:
      sparsh-network:
          aliases:
              - sparsh-api

  db:
    image: mysql:latest
    container_name: db
    build:
      context: db
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    # volumes:
    #   - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      sparsh-network:
          aliases:
              - db
    
  unit:
    image: unit:latest
    container_name: unit
    build:
      context: ./api/tests/unit
    command: pytest
    depends_on:
      - sparsh-api
    networks:
      sparsh-network:
          aliases:
              - unit

  integration:
    image: integration:latest
    container_name: integration
    build:
      context: ./api/tests/integration
    command: pytest
    depends_on:
      - sparsh-api
      - db
    networks:
      sparsh-network:
          aliases:
              - integration

  e2e:
    image: e2e:latest
    container_name: e2e
    build:
      context: ./api/tests/e2e
    command: pytest
    depends_on:
      - sparsh-api
      - db
    networks:
      sparsh-network:
          aliases:
              - e2e

  api-infra:
    image: api-infra:latest
    container_name: api-infra
    build:
      context: infra
      dockerfile: Dockerfile
    # volumes:
    #   - .:/app
    #   - /var/run/docker.sock:/var/run/docker.sock
    command: ["terraform", "apply", "-auto-approve"]
    networks:
      sparsh-network:
          aliases:
              - api-infra

networks:
  sparsh-network:
