# Global config
global: &global
  app_name: sparsh_api
  debug: true
  testing: false

# Test config
test:
  <<: *global
  testing: true
  env: test
  # api_key: my_api_key_test
  aws:
    access_key_id: fake-key-id
    region: us-west-2
  dynamo:
    endpoint_url: http://db:8000
    enable_local: true
    local_host: db
    local_port: 8000
# Dev config
dev:
  <<: *global
  env: dev
  # api_key: my_api_key_dev
  aws:
    access_key_id: fake-key-id
    region: us-west-2
  dynamo:
    endpoint_url: http://db:8000
    enable_local: true
    local_host: db
    local_port: 8000
# QA config
qa:
  <<: *global
  env: qa
  # api_key: my_api_key_qa
  aws:
    access_key_id: fake-key-id
    region: us-west-2
  dynamo:
    endpoint_url: 'https://dynamodb.us-west-2.amazonaws.com/'
    enable_local: false
# Prod config
prod:
  app_name: sparsh_api
  env: prod
  debug: false
  testing: false
  # api_key: my_api_key_prod
  aws:
    access_key_id: AKIAZOX23KYIL4ZGUTPW
    region: us-west-2
  dynamo:
    endpoint_url: 'https://dynamodb.us-west-2.amazonaws.com/'
    enable_local: false
