# Global config
global: &global
  app_name: sparsh_api
  debug: true
  testing: false

# Test config
test:
  <<: *global
  testing: true
  env: test
  # api_key: my_api_key_test
  aws:
    access_key_id: abcdefg123456
    secret_access_key: test_secret_key
    region: us-west-2
    # secret_name: test_secrets
  dynamo:
    enable_local: true
    local_host: 'localhost'
    local_port: 8000

# Dev config
dev:
  <<: *global
  env: dev
  # api_key: my_api_key_dev
  aws:
    access_key_id: abcdefg123456
    secret_access_key: dev_secret_key
    region: us-west-2
    # secret_name: dev_secrets
  dynamo:
    enable_local: true
    local_host: 'localhost'
    local_port: 8000

# QA config
qa:
  <<: *global
  env: qa
  # api_key: my_api_key_qa
  aws:
    access_key_id: abcdefg123456
    secret_access_key: qa_secret_key
    region: us-west-2
    # secret_name: qa_secrets

# Prod config
prod:
  app_name: sparsh_api
  env: prod
  debug: false
  testing: false
  # api_key: my_api_key_prod
  aws:
    access_key_id: AKIAZOX23KYIL4ZGUTPW
    region: us-west-2
    # secret_name: prod_secrets
