local:
  db:
    host: localhost
    port: 3306
    name: local_db
    user: root
    password: secret
  aws:
    access_key: abcdefg123456
    secret_key: 78910hijklmn
    region: us-west-2

production:
  db:
    host: prod.db.host.com
    port: 3306
    name: prod_db
    user: prod_user
    password: prod_secret
  aws:
    access_key: abcdefg123456
    secret_key: 78910hijklmn
    region: us-west-2
